[theme]
primaryColor = "#1E3A8A"
backgroundColor = "#F8FAFC"
secondaryBackgroundColor = "#E5E7EB"
textColor = "#1E293B"

[server]
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false